# This file is configured for deployment of the CantusDB project in local development.
# When building the project locally, replace the contents of docker-compose.yml with the
# contents of this file.

services:
  django:
    build:
      context: ./
      dockerfile: ./django/Dockerfile
      args:
        PROJECT_ENVIRONMENT: DEVELOPMENT
    container_name: cantusdb-django-1
    volumes:
      - ./:/code/cantusdb_project
      - static_volume:/resources/static
      - media_volume:/resources/media
      - api_cache_volume:/resources/api_cache
    env_file: ./config/envs/dev_env
    ports:
      - 3000:3000 # this mapping allows the VSCode Dev Containers extension to work
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /code/cantusdb_project/django/cantusdb_project
    command: [ "python", "manage.py", "runserver_plus", "0:8000" ]

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    container_name: cantusdb-nginx-1
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/resources/static
      - media_volume:/resources/media
      - api_cache_volume:/resources/api_cache
      - ./certificates:/etc/nginx/ssl/live
    restart: always
    depends_on:
      - django

  postgres:
    build:
      context: ./postgres
    env_file: ./config/envs/dev_env
    container_name: cantusdb-postgres-1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cantusdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    build:
      context: ./redis
    container_name: cantusdb-redis-1
    restart: always
    ports:
      - 6379:6379

  celery-worker:
    build:
      context: ./
      dockerfile: ./django/Dockerfile
      args:
        PROJECT_ENVIRONMENT: DEVELOPMENT
    container_name: cantusdb-celery-worker-1
    env_file: ./config/envs/dev_env
    volumes:
      - ./django/cantusdb_project:/code/cantusdb_project
    command: [ "celery", "-A", "cantusdb", "worker", "--loglevel=info", "--pool=solo", "--concurrency=1", "-E" ]

volumes:
  postgres_data:
  static_volume:
  media_volume:
  api_cache_volume:
