version: '3'

services:
  django:
    build:
      context: ./django
    volumes:
      - ./:/code/
      - static_volume:/resources/static
      - media_volume:/resources/media
    env_file: ./config/envs/dev_env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/resources/static
      - media_volume:/resources/media
      - certbot_data:/var/www/certbot/:ro
      - certificates:/etc/nginx/ssl/:ro
    depends_on:
      - django

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_data:/var/www/certbot/:rw
      - certificates:/etc/letsencrypt/:rw

  postgres:
    build:
      context: ./postgres
    env_file: ./config/envs/dev_env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot_data:
  certificates:
