version: '3'

services:
  django:
    build:
      context: ./django
    volumes:
      - ./:/code/
      - static_volume:/resources/static
      - media_volume:/resources/media
    env_file: ./config/envs/dev_env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/resources/static
      - media_volume:/resources/media
    restart: always
    depends_on:
      - django

  postgres:
    image: postgres:14-alpine
    env_file: ./config/envs/dev_env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
