from main_app.admin.century import CenturyAdmin
from main_app.admin.chant import ChantAdmin
from main_app.admin.differentia import DifferentiaAdmin
from main_app.admin.feast import FeastAdmin
from main_app.admin.genre import GenreAdmin
from main_app.admin.notation import NotationAdmin
from main_app.admin.service import ServiceAdmin
from main_app.admin.provenance import ProvenanceAdmin
from main_app.admin.segment import SegmentAdmin
from main_app.admin.sequence import SequenceAdmin
from main_app.admin.source import SourceAdmin
from main_app.admin.institution import InstitutionAdmin
from main_app.admin.institution_identifier import InstitutionIdentifierAdmin
from main_app.admin.project import ProjectAdmin
from main_app.admin.language import LanguageAdmin
from main_app.admin.site_banner import SiteBannerAdmin
from main_app.admin.data_check_config import DataCheckConfigAdmin
