# Generated by Django 4.2.3 on 2023-08-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_unaccent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chant",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.source",
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.source",
            ),
        ),
    ]
