# Generated by Django 4.2.3 on 2023-08-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_chant_source_alter_sequence_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chant",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.source"
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main_app.source"
            ),
        ),
    ]
