# Generated by Django 4.2.3 on 2023-09-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_alter_chant_ah_volume_alter_chant_cantus_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chant",
            name="melody_id",
            field=models.CharField(
                blank=True, max_length=63, null=True, verbose_name="melody ID"
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="melody_id",
            field=models.CharField(
                blank=True, max_length=63, null=True, verbose_name="melody ID"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="dact_id",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="DACT ID"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="fragmentarium_id",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="fragmentarium ID"
            ),
        ),
    ]
