# Generated by Django 4.2.3 on 2023-10-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_alter_chant_melody_id_alter_sequence_melody_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chant",
            old_name="differentia_new",
            new_name="differentiae_database",
        ),
        migrations.RenameField(
            model_name="sequence",
            old_name="differentia_new",
            new_name="differentiae_database",
        ),
    ]
