# Generated by Django 4.2.11 on 2024-04-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_differentia_chant_diff_db_sequence_diff_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="chant",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="The segment of the manuscript that contains this chant",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.segment",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                help_text="The segment of the manuscript that contains this chant",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.segment",
            ),
        ),
    ]
