# Generated by Django 4.2.11 on 2024-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_chant_segment_sequence_segment"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="exists_on_cantus_ultimus",
            field=models.BooleanField(default=False),
        ),
    ]
