# Generated by Django 4.2.11 on 2024-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_source_exists_on_cantus_ultimus"),
    ]

    operations = [
        migrations.AddField(
            model_name="chant",
            name="cm_melody_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Corpus Monodicum Melody ID",
            ),
        ),
        migrations.AddField(
            model_name="chant",
            name="incipit_of_refrain",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Incipit of the Refrain",
            ),
        ),
        migrations.AddField(
            model_name="chant",
            name="later_addition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chant",
            name="liturgical_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BD", "Benedicamus Domino"),
                    ("P", "Processional"),
                    ("H", "Historiae"),
                    ("D", "Dramatic Element"),
                ],
                max_length=10,
                null=True,
                verbose_name="Function",
            ),
        ),
        migrations.AddField(
            model_name="chant",
            name="polyphony",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2v", "2-voice polyphony"),
                    ("3v", "3-voice polyphony"),
                    ("4v", "4-voice polyphony"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="cm_melody_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Corpus Monodicum Melody ID",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="incipit_of_refrain",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Incipit of the Refrain",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="later_addition",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sequence",
            name="liturgical_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BD", "Benedicamus Domino"),
                    ("P", "Processional"),
                    ("H", "Historiae"),
                    ("D", "Dramatic Element"),
                ],
                max_length=10,
                null=True,
                verbose_name="Function",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="polyphony",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2v", "2-voice polyphony"),
                    ("3v", "3-voice polyphony"),
                    ("4v", "4-voice polyphony"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
