# Generated by Django 4.1.6 on 2024-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0011_chant_cm_melody_id_chant_incipit_of_refrain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="date",
            field=models.CharField(
                blank=True,
                help_text='Date of the source (e.g. "1200s", "1300-1350", etc.)',
                max_length=63,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="title",
            field=models.CharField(
                help_text="Full Source Identification (City, Archive, Shelf-mark)",
                max_length=255,
            ),
        ),
    ]
