# Generated by Django 4.1.6 on 2024-06-13 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0012_alter_source_date_alter_source_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RismSiglum",
        ),
    ]
