# Generated by Django 4.1.6 on 2024-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("main_app", "0016_institution_alternate_names_institution_region"),
        ("main_app", "0017_institution_country_alter_institution_city"),
    ]

    dependencies = [
        ("main_app", "0015_source_holding_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="alternate_names",
            field=models.TextField(
                blank=True,
                help_text="Enter alternate names on separate lines.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="region",
            field=models.CharField(
                blank=True,
                help_text='Province / State / Canton / County. Used to disambiguate cities, e.g., "London (Ontario)".',
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="country",
            field=models.CharField(default="s.l.", max_length=64),
        ),
        migrations.AlterField(
            model_name="institution",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City / Town / Village / Settlement",
                max_length=64,
                null=True,
            ),
        ),
    ]
