# Generated by Django 4.1.6 on 2024-06-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_app",
            "0016_institution_alternate_names_institution_region_squashed_0017_institution_country_alter_institution_city",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="former_sigla",
            field=models.TextField(
                blank=True, help_text="Enter former sigla on separate lines.", null=True
            ),
        ),
    ]
