# Generated by Django 4.2.11 on 2024-06-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_institution_former_sigla"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="rism_siglum",
        ),
        migrations.DeleteModel(
            name="RismSiglum",
        ),
    ]
