# Generated by Django 4.1.6 on 2024-06-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0020_institution_is_private_collector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="shelfmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
