# Generated by Django 4.1.6 on 2024-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0021_source_shelfmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="siglum",
            field=models.CharField(
                blank=True,
                help_text="RISM-style siglum + Shelf-mark (e.g. GB-Ob 202).",
                max_length=63,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Full Source Identification (City, Archive, Shelf-mark)",
                max_length=255,
                null=True,
            ),
        ),
    ]
