# Generated by Django 4.1.6 on 2024-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0022_alter_source_siglum_alter_source_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="siglum",
            field=models.CharField(
                blank=True,
                help_text="Reserved for assigned RISM sigla",
                max_length=32,
                null=True,
                verbose_name="RISM Siglum",
            ),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_private_collector", True),
                    ("siglum__isnull", False),
                    _negated=True,
                ),
                name="siglum_and_private_not_valid",
                violation_error_message="Siglum and Private Collector cannot both be specified.",
            ),
        ),
        migrations.AddConstraint(
            model_name="institution",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_private_collector", True),
                    ("siglum__isnull", False),
                    _connector="OR",
                ),
                name="at_least_one_of_siglum_or_private_collector",
                violation_error_message="At least one of Siglum or Private Collector must be specified.",
            ),
        ),
    ]
