# Generated by Django 4.2.11 on 2024-07-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0020_remove_chant_segment_remove_sequence_segment_project_and_more",
        ),
        ("main_app", "0023_alter_institution_siglum_and_more"),
    ]

    operations = []
