# Generated by Django 4.2.11 on 2024-07-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0025_alter_source_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="segment_m2m",
            field=models.ManyToManyField(
                blank=True,
                related_name="sources",
                to="main_app.segment",
                verbose_name="Segments",
            ),
        ),
    ]
