# Generated by Django 4.2.11 on 2024-08-07 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0026_source_segment_m2m"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Office",
            new_name="Service",
        ),
        migrations.RenameField(
            model_name="chant",
            old_name="office",
            new_name="service",
        ),
        migrations.RenameField(
            model_name="sequence",
            old_name="office",
            new_name="service",
        ),
    ]
