# Generated by Django 4.2.14 on 2024-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0027_rename_office_service_rename_office_chant_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["country", "city", "name"]},
        ),
        migrations.AlterField(
            model_name="institutionidentifier",
            name="identifier_type",
            field=models.IntegerField(
                choices=[
                    (1, "RISM Online"),
                    (2, "VIAF"),
                    (3, "Wikidata"),
                    (4, "GND (Gemeinsame Normdatei)"),
                    (5, "Bibliothèque national de France"),
                    (6, "Library of Congress"),
                    (7, "Digital Image Archive of Medieval Music"),
                ]
            ),
        ),
    ]
