# Generated by Django 4.2.14 on 2024-08-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_alter_institution_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="migrated_identifier",
            field=models.CharField(
                blank=True,
                help_text="Former Cantus identifier. Should not be used for new records.",
                max_length=64,
                null=True,
            ),
        ),
    ]
