# Generated by Django 4.2.14 on 2024-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_institution_migrated_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="is_private_collection",
            field=models.BooleanField(
                default=False,
                help_text="Mark this instititution as being a private collection. This is used to identify private \ncollectors regardless of whether they have a RISM siglum or not.\n",
            ),
        ),
    ]
