# Generated by Django 4.2.14 on 2024-08-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0030_institution_is_private_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="holding_institution",
            field=models.ForeignKey(
                default=19,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.institution",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="source",
            name="shelfmark",
            field=models.CharField(
                default="XX-NN",
                max_length=255,
            ),
        ),
    ]
