# Generated by Django 4.2.14 on 2024-10-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0030_institution_is_private_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A colloquial or commonly-used name for the source",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="production_method",
            field=models.IntegerField(
                choices=[(1, "Manuscript"), (2, "Printed")],
                default=1,
                verbose_name="Manuscript/Printed",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Full source"),
                    (2, "Fragment/Fragmented"),
                    (3, "Reconstruction"),
                ],
                default=1,
                verbose_name="Full Source/Fragment",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(default="[No Country]", max_length=64),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(default="[No Name]", max_length=255),
        ),
        migrations.AlterField(
            model_name="source",
            name="shelfmark",
            field=models.CharField(
                default="[No Shelfmark]",
                help_text="Primary Cantus Database identifier for the source (e.g. library shelfmark, DACT ID, etc.)",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="SourceIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Other catalogues"),
                            (2, "olim (Former shelfmark)"),
                            (3, "Alternative names"),
                            (4, "RISM Online"),
                        ]
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="main_app.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Identifier",
                "ordering": ("type",),
            },
        ),
    ]
