# Generated by Django 4.2.14 on 2024-10-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0031_source_name_source_production_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Complete source"),
                    (2, "Fragment"),
                    (3, "Reconstruction"),
                ],
                default=1,
                verbose_name="Complete Source/Fragment",
            ),
        ),
    ]
