# Generated by Django 4.2.14 on 2024-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0031_alter_source_holding_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A colloquial or commonly-used name for the source",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="shelfmark",
            field=models.CharField(max_length=255),
        ),
    ]
