# Generated by Django 4.2.14 on 2024-09-13 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0032_source_name_alter_source_shelfmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceIdentifier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Other catalogues"),
                            (2, "olim (Former shelfmark)"),
                            (3, "Alternative names"),
                            (4, "RISM Online"),
                        ]
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="main_app.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Identifier",
                "ordering": ("type",),
            },
        ),
    ]
