# Generated by Django 4.2.16 on 2024-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0032_alter_source_source_completeness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="production_method",
            field=models.IntegerField(
                choices=[(1, "Manuscript"), (2, "Print")],
                default=1,
                verbose_name="Manuscript/Print",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Complete or mostly complete"),
                    (2, "Fragment"),
                    (3, "Reconstruction"),
                    (4, "Fragmented"),
                ],
                default=1,
                verbose_name="Complete Source/Fragment",
            ),
        ),
    ]
