# Generated by Django 4.2.16 on 2025-01-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_alter_source_production_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Complete (or mostly complete)"),
                    (4, "Fragmented"),
                    (2, "Fragment"),
                    (3, "Reconstruction"),
                ],
                default=1,
                verbose_name="Complete Source/Fragment",
            ),
        ),
    ]
