# Generated by Django 4.2.16 on 2025-01-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_alter_source_production_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="all_chants_proofread",
            field=models.BooleanField(default=False),
        ),
    ]
