# Generated by Django 4.2.16 on 2025-01-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_source_all_chants_proofread"),
    ]

    operations = [
        migrations.RenameField(
            model_name="source",
            old_name="all_chants_proofread",
            new_name="all_chants_text_proofread",
        ),
    ]
