# Generated by Django 4.2.16 on 2025-02-06 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0034_alter_source_source_completeness"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="description_entered_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="entered_description_for_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
