# Generated by Django 4.2.16 on 2025-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_source_description_entered_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chant",
            name="other_fields_proofread",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sequence",
            name="other_fields_proofread",
            field=models.BooleanField(default=False),
        ),
    ]
