# Generated by Django 4.2.16 on 2025-04-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0036_chant_other_fields_proofread_and_more"),
        ("main_app", "0036_sourceurl"),
    ]

    operations = []
