# Generated by Django 4.2.16 on 2025-05-15 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0037_merge_20250411_1818"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProofreadingStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_volpiano_to_proofread", models.PositiveIntegerField(default=0)),
                (
                    "num_ms_full_text_to_proofread",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "num_ms_full_text_std_to_proofread",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "num_other_fields_to_proofread",
                    models.PositiveIntegerField(default=0),
                ),
                ("total_chants_in_source", models.PositiveIntegerField(default=0)),
                (
                    "total_chants_needing_proofread",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_proofread_opportunities",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_individual_fields_to_proofread",
                    models.PositiveIntegerField(default=0),
                ),
                ("percent_complete", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofreading_stats",
                        to="main_app.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proofreading Stats",
            },
        ),
    ]
