# Generated by Django 5.2.2 on 2025-08-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0038_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="chant",
            name="text_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.language",
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="text_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main_app.language",
            ),
        ),
    ]
