# Generated by Django 5.2.2 on 2025-10-01 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0039_chant_text_language_sequence_text_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="description_entered_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="entered_description_for_sources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="description written by",
            ),
        ),
    ]
