# Generated by Django 5.2.2 on 2026-06-19 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0040_alter_source_description_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="century",
            name="max_date",
            field=models.IntegerField(
                blank=True,
                help_text="End year of century (e.g., 1499 for 15th century). When left blank, auto-filled from the name on save if it matches a known pattern.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="century",
            name="min_date",
            field=models.IntegerField(
                blank=True,
                help_text="Start year of century (e.g., 1400 for 15th century). When left blank, auto-filled from the name on save if it matches a known pattern.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="source_data_contributed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="contributed_data_for_sources",
                to=settings.AUTH_USER_MODEL,
                verbose_name="source metadata contributed by",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Complete (or mostly complete)"),
                    (4, "Fragmented"),
                    (2, "Fragment"),
                    (3, "Reconstruction"),
                    (5, "Unknown"),
                ],
                default=1,
                verbose_name="Complete Source/Fragment",
            ),
        ),
        migrations.CreateModel(
            name="SiteBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="When unchecked, only superusers see the banner (as a preview). Check this to show it to all site visitors.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Markdown supported: [text](URL) for links, **bold**, *italic*. Press Enter for a new line.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Banner is automatically hidden at this time. Must be in the future, or leave blank to keep showing until you uncheck 'Is active'.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site banner",
                "verbose_name_plural": "site banner",
            },
        ),
    ]
