# Generated by Django 5.2.2 on 2026-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0041_century_max_date_century_min_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="description_markdown_draft",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="selected_bibliography_markdown_draft",
            field=models.TextField(blank=True, null=True),
        ),
    ]
