# Generated by Django 5.2.2 on 2026-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0041_century_max_date_century_min_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCheckConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        help_text="How often the data checks should run.",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All records"),
                            ("edited", "Only records edited in the period"),
                        ],
                        default="all",
                        help_text="All records: run checks against the full dataset. Only edited: restrict checks to records modified since the last run.",
                        max_length=20,
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set automatically after each completed run. Used to determine the editing window when scope is 'Only edited'.",
                        null=True,
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated email addresses that receive the data check report.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data check configuration",
                "verbose_name_plural": "Data check configurations",
            },
        ),
    ]
