# Generated by Django 5.2.2 on 2026-08-04 16:17

import main_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0042_datacheckconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCheckReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=main_app.storage.private_media_storage,
                        upload_to="data_check_reports/%Y/%m/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Data check report",
                "verbose_name_plural": "Data check reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
