# Generated by Django 5.2.2 on 2026-06-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Re-parented from 0042 onto production's migration leaf (0040): the
        # 0041/0042 Source migrations are not present on production, and
        # SiteBanner is a standalone table with no relation to Source.
        ("main_app", "0040_alter_source_description_entered_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="When unchecked, only superusers see the banner (as a preview). Check this to show it to all site visitors.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Markdown supported: [text](URL) for links, **bold**, *italic*. Press Enter for a new line.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional. Banner is automatically hidden at this time. Must be in the future, or leave blank to keep showing until you uncheck 'Is active'.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site banner",
                "verbose_name_plural": "site banner",
            },
        ),
    ]
