# Generated by Django 5.2.15 on 2026-08-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0043_datacheckreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_completeness",
            field=models.IntegerField(
                choices=[
                    (1, "Complete (or mostly complete)"),
                    (4, "Fragmented"),
                    (2, "Fragment"),
                    (3, "Reconstruction"),
                    (5, "Unknown"),
                ],
                default=1,
                verbose_name="Physical Status",
            ),
        ),
    ]
