# Generated by Django 5.2.15 on 2026-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0044_alter_source_source_completeness"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="description_html_legacy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="selected_bibliography_html_legacy",
            field=models.TextField(blank=True, null=True),
        ),
    ]
