# Generated by Django 5.2.16 on 2026-09-04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def rebuild_source_search_vectors(apps, schema_editor):
    # Import after AddField has run. The application helper also owns ongoing
    # maintenance, so the initial document has exactly the same contents.
    from main_app.source_search import rebuild_source_search_vectors as rebuild

    rebuild()


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0044_alter_source_source_completeness"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.RunPython(rebuild_source_search_vectors, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="source",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="source_search_vector_gin"
            ),
        ),
    ]
