# Generated by Django 5.2.16 on 2026-09-25 15:52

import main_app.models.text_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0045_normalize_text_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chant",
            name="image_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="chant",
            name="indexing_notes",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True, trim=False
            ),
        ),
        migrations.AlterField(
            model_name="chant",
            name="manuscript_full_text",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True,
                help_text="Enter the wording, word order and spellings as found in the manuscript, with abbreviations resolved to standard words. Use upper-case letters as found in the source. Retain “Xpistum” (Christum), “Ihc” (Jesus) and other instances of Greek characters with their closest approximations of Latin letters. Some punctuation signs and vertical dividing lines | are employed in this field. Repetenda and psalm cues can also be recorded here.",
            ),
        ),
        migrations.AlterField(
            model_name="chant",
            name="manuscript_full_text_std_spelling",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True,
                help_text='Manuscript full text with standardized spelling. Enter the words according to the manuscript but normalize their spellings following Classical Latin forms. Use upper-case letters for proper nouns, the first word of each chant, and the first word after "Alleluia" for Mass Alleluias. Punctuation is omitted.',
            ),
        ),
        migrations.AlterField(
            model_name="chant",
            name="manuscript_syllabized_full_text",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chant",
            name="volpiano",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chant",
            name="volpiano_intervals",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="chant",
            name="volpiano_notes",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="image_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="indexing_notes",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True, trim=False
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="manuscript_full_text",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True,
                help_text="Enter the wording, word order and spellings as found in the manuscript, with abbreviations resolved to standard words. Use upper-case letters as found in the source. Retain “Xpistum” (Christum), “Ihc” (Jesus) and other instances of Greek characters with their closest approximations of Latin letters. Some punctuation signs and vertical dividing lines | are employed in this field. Repetenda and psalm cues can also be recorded here.",
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="manuscript_full_text_std_spelling",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True,
                help_text='Manuscript full text with standardized spelling. Enter the words according to the manuscript but normalize their spellings following Classical Latin forms. Use upper-case letters for proper nouns, the first word of each chant, and the first word after "Alleluia" for Mass Alleluias. Punctuation is omitted.',
            ),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="manuscript_syllabized_full_text",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="volpiano",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="volpiano_intervals",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="volpiano_notes",
            field=main_app.models.text_field.NormalizedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="description",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True, trim=False
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="selected_bibliography",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True, trim=False
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="summary",
            field=main_app.models.text_field.NormalizedTextField(
                blank=True, trim=False
            ),
        ),
    ]
