# Generated by Django 5.2.2 on 2026-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0045_chantelement_unique_chant_element_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="chant",
            name="base_cantus_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="base Cantus ID"
            ),
        ),
        migrations.AddField(
            model_name="sequence",
            name="base_cantus_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="base Cantus ID"
            ),
        ),
    ]
