# Generated by Django 4.2.16 on 2025-03-18 16:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expiration",
                    models.DateField(
                        blank=True,
                        help_text="The date the user's membership in the group expires. Note that this is only checked for the `global viewer` group.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("is_staff", True), ("is_superuser", True)),
                    models.Q(("is_staff", False), ("is_superuser", False)),
                    _connector="OR",
                ),
                name="is_staff_xnor_is_superuser",
                violation_error_message="A user cannot be staff without being a superuser, and vice versa.",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.group"
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups_new",
            field=models.ManyToManyField(
                related_name="user_set",
                related_query_name="user",
                through="users.GroupMembership",
                to="users.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_group_membership"
            ),
        ),
    ]
