# Generated by Django 5.2.2 on 2025-08-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_group_groupmembership_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembership",
            name="expiration",
            field=models.DateField(
                blank=True,
                help_text="The date the user's membership in the group expires.",
                null=True,
            ),
        ),
    ]
